### ISSUE TITLE
User Story: Viewing products 

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/William-George-Retail-ltd#14]
As a **customer**, I would like to **view all of the  products available on the website** to enable me to **explore the full range of goods**.

Acceptance Criteria:

The homepage should clearly  display a "View All Products" or “Browse Range” button or link .

Clicking on the "View All Products" option should lead the user to a page displaying all available products.

There should be options to filter and sort products based on things like price, popularity, or category.

## Tasks
- [x] Create wirferames for UI 
- [ ] Create home and product apps
- [ ] Create base html and CSS
- [ ] Create html product page template and CSS
- [ ] Code model and view for the products
- [ ] Add products data to the database
- [ ] Test functionality
