### ISSUE TITLE
Epic: Site owner managing products and tracking orders

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/William-George-Retail-ltd#16]
As a **site owner** I would like **manage the products available to the user** and **track user orders and sales information** to enable me to ** effectively manage my business**.

## Tasks
- [ ]  chrissuttondev/William-George-Retail#3 
- [ ] chrissuttondev/William-George-Retail#18 
- [ ] chrissuttondev/William-George-Retail#2 
- [ ] chrissuttondev/William-George-Retail#1
