### ISSUE TITLE
User Story: Add a newsletter sign up option

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/William-George-Retail-ltd#17]
As a **site owner** I would like to **add a newsletter subscription sign up option to the website** to enable me to **build a mailing list and market new products, sales and deals to my customers**.

Acceptance Criteria

Newsletter CTA sign up  should be visible on the site, via homepage and or header.
Sign up form should include fields for user name and email address

## Tasks
- [ ] Create a visually appealing design for the newsletter signup form.
- [ ] Include fields for the customer's email address and an optional name.
- [ ] Add a clear call-to-action button, such as "Subscribe" or "Sign Up."
- [ ] Design form with html and CSS 
- [ ] Create a django model to store user information in the database
- [ ] Create views and urls
