### ISSUE TITLE
Epic: Select items and checkout

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/William-George-Retail-ltd#19]
As a **user** I would like to **add products to a shopping cart and checkout securely** so that I can **quickly and easily purchase the products I want**

Acceptance criteria in Tasks

## Tasks
- [ ] chrissuttondev/William-George-Retail#13 
- [ ] chrissuttondev/William-George-Retail#12 
- [ ] chrissuttondev/William-George-Retail#11 
- [ ] chrissuttondev/William-George-Retail#10 
- [ ] chrissuttondev/William-George-Retail#4
