### ISSUE TITLE
Epic User Story: Authentication

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/William-George-Retail-ltd#22]
As a user , I am directed to authenticate and/or register when coming to the website.

Acceptance Criteria within tasks.

## Task
- [ ] chrissuttondev/William-George-Retail#9 
- [ ] chrissuttondev/William-George-Retail#8 
- [ ] chrissuttondev/William-George-Retail#7 
- [ ] chrissuttondev/William-George-Retail#5
