### ISSUE TITLE
User Story: Searching Products

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/William-George-Retail-ltd#35]
As a **customer**, I would like to **search for specific products** to enable me to **quickly find what I’m looking for**.

Acceptance Criteria:

The search bar should be easily accessible from any page on the website.

Typing in a product name or keyword and hitting enter should display relevant search results.

## Tasks

- [ ] Create visually appealing search bar, displayed in header or on products page
- [ ] Create models, views and html template for products page
- [ ] Implement logic to handle user search queries
